### ISSUE TITLE
[Feature] Fast layer full name copy

### ISSUE THREAD

**Issue by MyisCARRY** [Napster653/SquadMaps#27]
Hi great app.
Could you add button, which will automatically copy layer name to clipboard? For example: "Gorodok AAS v1 (USA vs RUS)"

**Comment by Napster653** [comment]
That's a great idea! I'll add buttons to copy the layer name and the raw name so server admins can copy the layer names to their servers' map lists.

**Comment by Ivoz** [comment]
Sometimes I use this site basically so I can choose a layer for `AdminSetNextLayer <layer>` so that would be quite handy

**Comment by Napster653** [comment]
Done
