### ISSUE TITLE
Search for mapname, gamelayer and version individually

### ISSUE THREAD

**Issue by TomNedry** [Napster653/SquadMaps#43]
### Feature Description

I like to propose to parse the search field for mapname, gamelayer and version individually.

Examples:

a) 
Search Input: "go ra 1" 
Result:
Gorodok RAAS v1
Goose Bay RAAS v1

b) 
Search Input: "fa i 2"
Result: "Fallujah Invasion v2"

c) 
Search Input: "har r"
Result: All RAAS layers of Harju

**Comment by mahtoid** [comment]
This has been solved on the latest version - I do recall we had a conversation on Discord. 

Let me know if you feel there is still some more to be solved around this.
[https://squadmaps.com](https://squadmaps.com)

💜

**Comment by TomNedry** [comment]
Thx!
