### ISSUE TITLE
Link faction images to respective squad fandom faction page with "open in new tab" link

### ISSUE THREAD

**Issue by D4n2021** [Napster653/SquadMaps#44]
### Feature Description

So that when clicking the Canadian and russian flags in this example screenshot, that they open 
https://squad.fandom.com/wiki/Canadian_Army
and
https://squad.fandom.com/wiki/Russian_Ground_Forces
respectively in new browser tabs.

![Screenshot_20231227-002728~2](https://github.com/mahtoid/SquadMaps/assets/20766261/032afa75-6e07-4906-a413-260875884655)

**Comment by mahtoid** [comment]
Closing this feature request out.

We discussed on Discord and I have added a solution to our backlog. Currently this isn't included in v1, so we don't see to feature match and already have a long list of things we want to get done which require a lot more focus (compared to the solution we discussed).

Expect this in the future, but unknown when.
