### ISSUE TITLE
Return to previous search results feature or make the results a pop-up

### ISSUE THREAD

**Issue by lbzepoqo** [Napster653/SquadMaps#45]
### Feature Description

Currently, when searching for anything and clicking a result there are only two (2) options to return:
1. Return to maps
2. Return to layer selection

In my case I was searching for all AAS layers, or even a specific mode of a layer and it's a bummer than I must retype my search again because those are the only options above.

https://github.com/mahtoid/SquadMaps/assets/49586590/c56ffcf7-5032-4529-b92f-2f99a103047e

## My suggestions would be:
1. Have a third option `Return to previous search results`; or
2. Make the results a pop-up instead of opening a new page

**Comment by mahtoid** [comment]
Hey, sorry for the delay in responding!

This is solved under the latest version which has just been released, [https://squadmaps.com](https://squadmaps.com).
Clicking the back arrow will navigate you back to where you just came from - with whatever filters you set up.

Re-open if you still feel like it is an issue 💜
