### ISSUE TITLE
Map doesn't specify which main belongs to what team on AAS layers

### ISSUE THREAD

**Issue by Svdovych** [Napster653/SquadMaps#46]
### Bug Description

![image](https://github.com/mahtoid/SquadMaps/assets/23632605/01c3199a-f0b9-4f87-a8bb-34f28611862e)
Reproducible on all AAS and Skirmish layers

**Comment by mahtoid** [comment]
Eek, nice spot! I will get a solve on this ASAP

**Comment by mahtoid** [comment]
This has been solved in the update we did for Squad 7.1, let me know if you find any other issues! 💜
