### ISSUE TITLE
Squad v7.1 : New map Sanxian

### ISSUE THREAD

**Issue by Toast-arch** [Napster653/SquadMaps#47]
### Feature Description

Hello ! Any plans on adding support for the new map Sanxian ? I'm down to do it myself if you'll allow me.

**Comment by freddyrangel** [comment]
I thought it was supported: [Sanxian Map](https://squadmaps.com/?map=Sanxian+Islands)

**Comment by mahtoid** [comment]
Hey, sorry for the delay on the update. I didn't see this issue in time, but we indeed updated the day after. 
Each update we have to wait for the Squad Pipeline to update so we have the latest data to display - we can't always do same-day update. 

Terribly sorry! 💜

**Comment by freddyrangel** [comment]
> Hey, sorry for the delay on the update. I didn't see this issue in time, but we indeed updated the day after. Each update we have to wait for the Squad Pipeline to update so we have the latest data to display - we can't always do same-day update.
> 
> Terribly sorry! 💜

Hey no worries dude. Maybe this issue isn't the best place to ask this but I've been wondering if the code on GitHub is up to date with what's in production. I was meaning to dive into the code last month and see if there's something I can contribute but it doesn't quite seem to match what I see online. Or maybe I'm missing something?

**Comment by mahtoid** [comment]
@freddyrangel Hey - not yet. The code which is public here is SquadMaps v1, v2 is currently still closed-source. I do plan to make it open source again at some point in the future, but we need to clean up the code a little and I also want it to be a little further feature padded first. 

Feel free to [join the Discord](https://discord.mahto.id) for updates, it's also a better way to communicate. I can often suck at being responsive on Github.
