### ISSUE TITLE
Incorrectly showing double-point cap zones

### ISSUE THREAD

**Issue by Svdovych** [Napster653/SquadMaps#49]
### Bug Description

![image](https://github.com/mahtoid/SquadMaps/assets/23632605/c679c99d-52bb-4a9a-9c8d-efd3399f64be)
![image](https://github.com/mahtoid/SquadMaps/assets/23632605/959f2bab-e390-4a42-a5a5-7b36093177b7)
Issue is clearly seen on images

**Comment by mahtoid** [comment]
Nice spot! I've added that on to our list to solve. I'll keep this ticket open until we've deployed the fix 😄

**Comment by mahtoid** [comment]
Closing out, Gorodok RAAS v2 no longer exists
