### ISSUE TITLE
Incorrect Cap for Harju RAAS V1

### ISSUE THREAD

**Issue by MJH1606** [Napster653/SquadMaps#50]
### Bug Description

For Harju RAAS v1, the caps have not been updated.
![image](https://github.com/mahtoid/SquadMaps/assets/105934387/4cb6f835-feea-4d44-9aa6-3847f8c705d9)
On SquadMaps, the cap does not go there at all.
![image](https://github.com/mahtoid/SquadMaps/assets/105934387/1e04de56-2f42-41b5-bc42-332dd2fcab83)

**Comment by mahtoid** [comment]
Data issue, not much we can do about this. I'll let Tim know but I doubt we'll find a solution.
