### ISSUE TITLE
Missing Sanxian map images

### ISSUE THREAD

**Issue by DA-AshleyJ** [Napster653/SquadMaps#51]
### Bug Description

Looked into the Repo and cannot find any Sanxian map images.

**Comment by mahtoid** [comment]
You can find the Sanxian image [here](https://github.com/mahtoid/SquadUtils/blob/main/TGA/T_Sanxian_Minimap_Large.TGA).

This is inside the [SquadUtils](https://github.com/mahtoid/SquadUtils/) repo. We no longer take screenshots as that's very time consuming.
