### ISSUE TITLE
Lashkar Valley RAAS V1 does'nt work

### ISSUE THREAD

**Issue by Toast-arch** [Napster653/SquadMaps#52]
### Bug Description

When I was trying to access the Lashkar Valley RAAS V1, I access the Lashkar Valley sub menu, and then click on the Lashkar Valley RAAS V1. the page then goes blank and SquadMaps stops working until I refresh back to the main page. Check this link: https://squadmaps.com/map?name=Lashkar%20Valley&layer=RAAS%20v1

**Comment by mahtoid** [comment]
This has been solved and deployed. Thank you for the Github Issue, if you spot any more issues let me know!💜
